import { resolveI18nText, type TranslateFn } from '@mindwtr/core';

// The keys settings pages read through the `t` prop. Every key resolves to a
// `settings.<key>` string in packages/core/src/i18n (or an explicit override
// below) — this array is only the roster of keys, not their text. Localized
// text lives entirely in packages/core/src/i18n/locales/*.ts so translators
// and locale-parity.test.ts can see it.
export const SETTINGS_LABEL_KEYS = [
    'title',
    'general',
    'data',
    'integrations',
    'advanced',
    'subtitle',
    'searchPlaceholder',
    'back',
    'features',
    'featuresDesc',
    'lookAndFeel',
    'localization',
    'regionalFormats',
    'input',
    'windowBehavior',
    'keyboardAndWindow',
    'appearance',
    'density',
    'densityDesc',
    'densityComfortable',
    'densityCompact',
    'densityCondensed',
    'textSize',
    'textSizeDesc',
    'textSizeSmall',
    'textSizeDefault',
    'textSizeLarge',
    'textSizeExtraLarge',
    'fontFamily',
    'fontFamilyDesc',
    'fontFamilyDefault',
    'fontFamilyPlaceholder',
    'showTaskAge',
    'showTaskAgeDesc',
    'sidebarViews',
    'sidebarViewsDesc',
    'navAgenda',
    'navSomeday',
    'navWaiting',
    'navReference',
    'navCalendar',
    'navReview',
    'navContexts',
    'navBoard',
    'navTimeline',
    'navHistory',
    'navTrash',
    'gtd',
    'gtdDesc',
    'settingsSaveFailed',
    'pomodoroAutoStartNotice',
    'inboxProcessing',
    'inboxProcessingDesc',
    'inboxDefaultMode',
    'inboxModeGuided',
    'inboxModeQuick',
    'inboxTwoMinuteEnabled',
    'inboxTwoMinuteFirst',
    'inboxProjectFirst',
    'inboxContextStepEnabled',
    'inboxScheduleEnabled',
    'inboxReferenceEnabled',
    'captureDefault',
    'captureDefaultDesc',
    'captureDefaultText',
    'captureDefaultAudio',
    'captureSaveAudio',
    'captureSaveAudioDesc',
    'quickAddAutoClean',
    'quickAddAutoCleanDesc',
    'naturalLanguageDates',
    'naturalLanguageDatesDesc',
    'markdownEditorAssist',
    'markdownEditorAssistDesc',
    'autoArchive',
    'autoArchiveDesc',
    'autoArchiveNever',
    'autoArchiveDayUnit',
    'defaultScheduleTime',
    'defaultScheduleTimeDesc',
    'defaultArea',
    'defaultAreaDesc',
    'defaultAreaNone',
    'defaultAreaActive',
    'focusTaskLimit',
    'focusTaskLimitDesc',
    'defaultProjectFlowMode',
    'defaultProjectFlowModeDesc',
    'projectFlowParallel',
    'projectFlowSequential',
    'enableTimeEstimates',
    'language',
    'weekStart',
    'weekStartSunday',
    'weekStartSystem',
    'weekStartMonday',
    'weekStartSaturday',
    'dateFormat',
    'dateFormatSystem',
    'dateFormatDmy',
    'dateFormatMdy',
    'dateFormatYmd',
    'calendarSystem',
    'calendarSystemGregorian',
    'calendarSystemJalali',
    'timeFormat',
    'timeFormatSystem',
    'timeFormat12h',
    'timeFormat24h',
    'keybindings',
    'keybindingsDesc',
    'undoNotifications',
    'undoNotificationsDesc',
    'globalQuickAddShortcut',
    'globalQuickAddShortcutDesc',
    'globalQuickAddFlatpakDesc',
    'globalQuickAddFlatpakCommand',
    'globalQuickAddFlatpakCommandDesc',
    'keybindingStandard',
    'keybindingVim',
    'keybindingEmacs',
    'viewShortcuts',
    'windowDecorations',
    'windowDecorationsDesc',
    'closeBehavior',
    'closeBehaviorDesc',
    'closeBehaviorAsk',
    'closeBehaviorTray',
    'closeBehaviorQuit',
    'launchAtStartup',
    'launchAtStartupDesc',
    'showTray',
    'showTrayDesc',
    'automation',
    'rendering',
    'softwareRendering',
    'softwareRenderingDesc',
    'network',
    'localApiServer',
    'localApiPort',
    'localApiPortDesc',
    'localApiToken',
    'localApiTokenDesc',
    'localApiSecurityNote',
    'localApiStopped',
    'localApiUnavailable',
    'localApiPortInvalid',
    'taskEditorLayout',
    'taskEditorLayoutDesc',
    'taskEditorLayoutHint',
    'taskEditorPresentation',
    'taskEditorPresentationDesc',
    'taskEditorPresentationInline',
    'taskEditorPresentationInlineDesc',
    'taskEditorPresentationModal',
    'taskEditorPresentationModalDesc',
    'taskEditorLayoutReset',
    'taskEditorSection',
    'taskEditorDefaultOpen',
    'taskEditorOpenByDefault',
    'taskEditorDefaultOpenDesc',
    'taskEditorFieldStatus',
    'taskEditorFieldProject',
    'taskEditorFieldSection',
    'taskEditorFieldArea',
    'taskEditorFieldPriority',
    'taskEditorFieldEnergyLevel',
    'taskEditorFieldAssignedTo',
    'taskEditorFieldContexts',
    'taskEditorFieldDescription',
    'taskEditorFieldLocation',
    'taskEditorFieldTags',
    'taskEditorFieldTimeEstimate',
    'taskEditorFieldRecurrence',
    'taskEditorFieldStartTime',
    'taskEditorFieldDueDate',
    'taskEditorFieldReviewAt',
    'taskEditorFieldAttachments',
    'taskEditorFieldChecklist',
    'taskEditorFieldTextDirection',
    'taskEditorSectionBasic',
    'taskEditorSectionScheduling',
    'taskEditorSectionOrganization',
    'taskEditorSectionDetails',
    'featurePriorities',
    'featurePrioritiesDesc',
    'featureTimeEstimates',
    'featureTimeEstimatesDesc',
    'featurePomodoro',
    'featurePomodoroDesc',
    'featureTimeline',
    'featureTimelineDesc',
    'pomodoroCustomPreset',
    'pomodoroCustomPresetDesc',
    'pomodoroFocusMinutes',
    'pomodoroBreakMinutes',
    'pomodoroLinkTask',
    'pomodoroLinkTaskDesc',
    'pomodoroAutoStartBreaks',
    'pomodoroAutoStartBreaksDesc',
    'pomodoroAutoStartFocus',
    'pomodoroAutoStartFocusDesc',
    'pomodoroCompletionAlert',
    'pomodoroCompletionAlertDesc',
    'notifications',
    'notificationsDesc',
    'notificationsEnable',
    'startDateNotifications',
    'startDateNotificationsDesc',
    'dueDateNotifications',
    'dueDateNotificationsDesc',
    'reviewAtNotifications',
    'reviewAtNotificationsDesc',
    'ai',
    'aiDesc',
    'aiUsageTitle',
    'aiUsageClarify',
    'aiUsageBreakdown',
    'aiUsageSuggestions',
    'aiUsageReview',
    'aiEnable',
    'aiProvider',
    'aiProviderOpenAI',
    'aiProviderGemini',
    'aiProviderAnthropic',
    'aiModel',
    'aiBaseUrl',
    'aiBaseUrlHint',
    'aiBaseUrlModelHint',
    'aiExtraBodyParams',
    'aiExtraBodyParamsDesc',
    'aiExtraBodyParamsHint',
    'aiExtraBodyParamsInvalid',
    'aiExtraBodyParamsSave',
    'aiApiKey',
    'aiApiKeyHint',
    'aiReasoning',
    'aiReasoningHint',
    'aiEffortLow',
    'aiEffortMedium',
    'aiEffortHigh',
    'aiCopilotModel',
    'aiCopilotHint',
    'aiAdvanced',
    'aiRequestTimeout',
    'aiRequestTimeoutDesc',
    'aiRequestTimeoutSeconds',
    'aiConsentTitle',
    'aiConsentDescription',
    'aiConsentCancel',
    'aiConsentAgree',
    'aiThinkingBudget',
    'aiThinkingHint',
    'aiThinkingEnable',
    'aiThinkingEnableDesc',
    'aiThinkingOff',
    'aiThinkingLow',
    'aiThinkingMedium',
    'aiThinkingHigh',
    'speechTitle',
    'speechDesc',
    'speechEnable',
    'speechProvider',
    'speechProviderOffline',
    'speechProviderParakeet',
    'speechModel',
    'speechBaseUrl',
    'speechBaseUrlHint',
    'speechOfflineModel',
    'speechOfflineModelDesc',
    'speechParakeetModelDesc',
    'speechParakeetModelPath',
    'speechParakeetModelPathPlaceholder',
    'speechOfflineReady',
    'speechOfflineNotDownloaded',
    'speechOfflineEstimatedSize',
    'speechOfflinePathSet',
    'speechOfflineDownload',
    'speechOfflineDownloadSuccess',
    'speechOfflineDelete',
    'speechOfflineDownloadRuntime',
    'speechOfflineDownloadModel',
    'speechOfflineInstalling',
    'speechOfflineDownloadError',
    'speechLanguage',
    'speechLanguageHint',
    'speechLanguageAuto',
    'speechMode',
    'speechModeHint',
    'speechModeSmart',
    'speechModeTranscript',
    'speechFieldStrategy',
    'speechFieldStrategyHint',
    'speechFieldSmart',
    'speechFieldTitle',
    'speechFieldDescription',
    'dailyDigest',
    'dailyDigestDesc',
    'dailyDigestMorning',
    'dailyDigestEvening',
    'weeklyReview',
    'weeklyReviewDesc',
    'weeklyReviewDay',
    'weeklyReviewTime',
    'weeklyReviewConfig',
    'weeklyReviewConfigDesc',
    'weeklyReviewIncludeContextsStep',
    'weeklyReviewIncludeContextsStepDesc',
    'on',
    'off',
    'visible',
    'hidden',
    'manage',
    'cancel',
    'sandboxWorkspace',
    'sandboxDescription',
    'sandboxSwitching',
    'sandboxSwitchFailed',
    'sandboxConfirmTitle',
    'sandboxConfirmDescription',
    'sandboxEnter',
    'backup',
    'backupDesc',
    'importData',
    'importDataDesc',
    'gettingStartedContentAction',
    'gettingStartedContentDesc',
    'gettingStartedContentConfirmTitle',
    'gettingStartedContentConfirmDesc',
    'gettingStartedContentConfirm',
    'gettingStartedContentContinueTitle',
    'gettingStartedContentContinueDesc',
    'calendarIntegrationGuideTitle',
    'obsidianIntegrationGuideTitle',
    'emailCaptureGuideTitle',
    'syncSetupGuideTitle',
    'syncSetupGuideDesc',
    'syncEncryptionGuideTitle',
    'importSetupGuideTitle',
    'importSetupGuideDesc',
    'exportBackup',
    'exportCsv',
    'exportCsvDesc',
    'exportTaskNotes',
    'exportTaskNotesDesc',
    'exportBackupDesc',
    'restoreBackup',
    'restoreBackupDesc',
    'mergeBackup',
    'mergeBackupDesc',
    'importTodoist',
    'importTodoistDesc',
    'importTickTick',
    'importTickTickDesc',
    'importDgt',
    'importDgtDesc',
    'importOmniFocus',
    'importOmniFocusDesc',
    'importMindwtrCsv',
    'importMindwtrCsvDesc',
    'diagnostics',
    'diagnosticsDesc',
    'analyticsHeartbeat',
    'analyticsHeartbeatDesc',
    'analyticsHeartbeatDisableTitle',
    'analyticsHeartbeatDisableDesc',
    'analyticsHeartbeatDisableConfirm',
    'analyticsHeartbeatKeepEnabled',
    'debugLogging',
    'debugLoggingDesc',
    'logFile',
    'clearLog',
    'saveLog',
    'sync',
    'syncDescription',
    'syncBackend',
    'syncBackendOff',
    'syncBackendFile',
    'syncBackendWebdav',
    'syncBackendCloud',
    'syncBackendCloudkit',
    'syncBackendChoiceHint',
    'syncBackendGroupCloud',
    'syncBackendGroupCloudDesc',
    'syncBackendGroupFile',
    'syncBackendGroupFileDesc',
    'syncBackendGroupAdvanced',
    'syncBackendGroupAdvancedDesc',
    'networkProxyUrl',
    'networkProxyUrlDesc',
    'networkProxyUrlHint',
    'networkProxyInvalid',
    'networkProxySave',
    'syncPreferences',
    'syncPreferencesDesc',
    'syncPreferenceAppearance',
    'syncPreferenceLanguage',
    'syncPreferenceGtd',
    'syncPreferenceSavedFilters',
    'syncPreferenceExternalCalendars',
    'syncPreferenceAi',
    'syncPreferenceAiHint',
    'backgroundSync',
    'backgroundSyncDesc',
    'attachmentsCleanup',
    'attachmentsCleanupDesc',
    'attachmentsCleanupLastRun',
    'attachmentsCleanupNever',
    'attachmentsCleanupPendingDeletes',
    'attachmentsCleanupPendingDeletesClear',
    'attachmentsCleanupPendingDeletesConfirm',
    'attachmentsCleanupPendingDeletesConfirmAction',
    'attachmentsCleanupPendingDeletesConfirmTitle',
    'attachmentsCleanupRun',
    'attachmentsCleanupRunning',
    'syncEncryption',
    'syncEncryptionDesc',
    'syncEncryptionEnable',
    'syncEncryptionPassphrase',
    'syncEncryptionPassphraseConfirm',
    'syncEncryptionCurrentPassphrase',
    'syncEncryptionNewPassphrase',
    'syncEncryptionShowPassphrase',
    'syncEncryptionGenerate',
    'syncEncryptionGeneratedHint',
    'syncEncryptionWarningLost',
    'syncEncryptionWarningDevices',
    'syncEncryptionErrorMismatch',
    'syncEncryptionErrorWrongPassphrase',
    'syncEncryptionErrorGeneric',
    'syncEncryptionErrorRotationFirst',
    'syncEncryptionErrorBackendRequired',
    'syncEncryptionErrorBackendIncompatible',
    'syncEncryptionErrorTransitionIncomplete',
    'syncEncryptionCleanupDeferred',
    'syncEncryptionNoEncryptedRemote',
    'syncEncryptionLockedRecheckHint',
    'syncEncryptionStateUnavailable',
    'syncEncryptionRetry',
    'syncEncryptionEnableBeforeFirstSyncHint',
    'syncEncryptionProgressAttachments',
    'syncEncryptionProgressDocuments',
    'syncEncryptionStatusOn',
    'syncEncryptionChange',
    'syncEncryptionDisable',
    'syncEncryptionDisableWarning',
    'syncEncryptionDisableWarningNoBackend',
    'syncEncryptionRemotePlaintextDesc',
    'syncEncryptionLockedTitle',
    'syncEncryptionLockedDesc',
    'syncEncryptionUnlock',
    'syncEncryptionDecline',
    'syncEncryptionPausedDesc',
    'syncEncryptionCancel',
    'calendar',
    'calendarDesc',
    'externalCalendars',
    'calendarName',
    'calendarUrl',
    'calendarAdd',
    'calendarChooseLocalFile',
    'calendarRemove',
    'calendarColorAuto',
    'calendarSystemTitle',
    'calendarSystemDesc',
    'calendarSystemStatus',
    'calendarSystemPermissionGranted',
    'calendarSystemPermissionUndetermined',
    'calendarSystemPermissionDenied',
    'calendarSystemPermissionUnsupported',
    'calendarSystemRequestAccess',
    'calendarSystemDeniedHint',
    'calendarPushTitle',
    'calendarPushDesc',
    'calendarPushEnable',
    'calendarPushTarget',
    'calendarPushManagedTarget',
    'calendarPushRefresh',
    'calendarPushLoading',
    'calendarPushTargetHint',
    'syncFolderLocation',
    'savePath',
    'browse',
    'testFolder',
    'testingFolder',
    'folderTestSucceeded',
    'portalPathNote',
    'syncNow',
    'syncing',
    'syncQueued',
    'pathHint',
    'webdavUrl',
    'webdavUsername',
    'webdavPassword',
    'webdavSave',
    'testConnection',
    'cloudTestHint',
    'webdavTestHint',
    'webdavTestAccessibility',
    'webdavHint',
    'allowInsecureHttp',
    'allowInsecureHttpHint',
    'invalidUrlHttp',
    'cloudUrl',
    'cloudToken',
    'cloudTokenHint',
    'cloudRememberToken',
    'cloudRememberTokenHint',
    'cloudSave',
    'cloudHint',
    'cloudProvider',
    'cloudProviderSelfHosted',
    'cloudProviderDropbox',
    'cloudProviderCloudkit',
    'cloudkitDesc',
    'calendarFeed',
    'calendarFeedDesc',
    'calendarFeedWarning',
    'calendarFeedNone',
    'calendarFeedCopy',
    'calendarFeedGenerate',
    'calendarFeedRegenerate',
    'calendarFeedRevoke',
    'dropboxAppKey',
    'dropboxAppKeyHint',
    'dropboxRedirectUri',
    'dropboxStatus',
    'dropboxConnected',
    'dropboxNotConnected',
    'dropboxConnect',
    'dropboxDisconnect',
    'dropboxTest',
    'dropboxTestReachable',
    'dropboxTestFailed',
    'obsidianVault',
    'obsidianVaultDesc',
    'obsidianEnable',
    'obsidianVaultPath',
    'obsidianVaultPathHint',
    'obsidianDetectedVaults',
    'obsidianScanFolders',
    'obsidianScanFoldersHint',
    'obsidianInboxFile',
    'obsidianInboxFileHint',
    'obsidianDataview',
    'obsidianDataviewDesc',
    'obsidianDataviewMetadata',
    'obsidianDataviewMetadataHint',
    'obsidianTaskNotes',
    'obsidianTaskNotesDesc',
    'obsidianTaskNotesIncludeArchived',
    'obsidianTaskNotesIncludeArchivedHint',
    'obsidianNewTaskFormat',
    'obsidianNewTaskFormatHint',
    'obsidianNewTaskFormatAuto',
    'obsidianNewTaskFormatInline',
    'obsidianNewTaskFormatTaskNotes',
    'obsidianWatching',
    'obsidianWatcherUnavailable',
    'obsidianSave',
    'obsidianRemove',
    'obsidianRescan',
    'obsidianRescanning',
    'obsidianLastScanned',
    'obsidianNeverScanned',
    'obsidianMissingMarker',
    'obsidianChooseVaultFailed',
    'obsidianSaveFailed',
    'obsidianRemoveFailed',
    'obsidianScanFailed',
    'obsidianScanSuccess',
    'emailCapture',
    'emailCaptureDesc',
    'emailCaptureHost',
    'emailCapturePort',
    'emailCaptureUsername',
    'emailCapturePassword',
    'emailCapturePasswordHint',
    'emailCapturePasswordStored',
    'emailCaptureFolder',
    'emailCaptureFolderHint',
    'emailCaptureSave',
    'emailCaptureRemove',
    'emailCaptureCheckNow',
    'emailCaptureChecking',
    'emailCaptureLastChecked',
    'emailCaptureNeverChecked',
    'emailCaptureImportedCount',
    'emailCaptureSaveFailed',
    'dingtalkSync',
    'dingtalkSyncDesc',
    'dingtalkMcpUrl',
    'dingtalkMcpUrlHint',
    'dingtalkMcpUrlStored',
    'dingtalkSave',
    'dingtalkSyncNow',
    'dingtalkSyncing',
    'dingtalkLastSynced',
    'dingtalkNeverSynced',
    'dingtalkImportedCount',
    'dingtalkCompletedCount',
    'dingtalkAuthFailed',
    'dingtalkSaveFailed',
    'dingtalkSyncFailed',
    'lastSync',
    'lastSyncNever',
    'lastSyncSuccess',
    'lastSyncError',
    'lastSyncConflict',
    'lastSyncConflicts',
    'tasks',
    'projects',
    'lastSyncSkew',
    'lastSyncAdjusted',
    'lastSyncConflictIds',
    'syncConflictKeptThisDevice',
    'syncConflictKeptOtherDevice',
    'syncConflictChanged',
    'syncConflictDeleteRestore',
    'syncConflictMore',
    'syncHistory',
    'syncHistoryBackend',
    'syncHistoryType',
    'syncHistoryDetails',
    'recoverySnapshots',
    'recoverySnapshotsDesc',
    'recoverySnapshotsLoading',
    'recoverySnapshotsEmpty',
    'recoverySnapshotsRestore',
    'recoverySnapshotsRestoreNamed',
    'recoverySnapshotsConfirm',
    'recoverySnapshotsConfirmTitle',
    'recoverySnapshotsConfirmCancel',
    'about',
    'version',
    'installChannel',
    'developer',
    'website',
    'github',
    'documentation',
    'videoTutorials',
    'privacy',
    'terms',
    'sponsorProject',
    'license',
    'feedback',
    'feedbackDesc',
    'feedbackCategory',
    'feedbackCategoryBug',
    'feedbackCategoryFeature',
    'feedbackCategoryOther',
    'feedbackMessage',
    'feedbackMessagePlaceholder',
    'feedbackMessagePlaceholderBug',
    'feedbackMessagePlaceholderFeature',
    'feedbackMessagePlaceholderOther',
    'feedbackWhere',
    'feedbackWherePlaceholder',
    'feedbackWhereMessagePrefix',
    'feedbackWhereInbox',
    'feedbackWhereFocus',
    'feedbackWhereProjects',
    'feedbackWhereReview',
    'feedbackWhereSettings',
    'feedbackWhereSync',
    'feedbackWhereImportExport',
    'feedbackWhereNotifications',
    'feedbackWhereOther',
    'feedbackEmail',
    'feedbackEmailPlaceholder',
    'feedbackIncludeDiagnostics',
    'feedbackIncludeDiagnosticsDesc',
    'feedbackPrivacy',
    'feedbackSubmit',
    'feedbackSending',
    'feedbackSent',
    'feedbackFailed',
    'feedbackUnavailable',
    'feedbackUnavailableDesc',
    'feedbackOpenGitHubIssue',
    'feedbackGitHubDesc',
    'feedbackOpenGitHubDiscussion',
    'feedbackRequired',
    'feedbackInvalidEmail',
    'checkForUpdates',
    'checkStoreUpdates',
    'checking',
    'upToDate',
    'updateAvailable',
    'checkFailed',
    'updateRateLimited',
    'languagePartlyTranslated',
    'storeUpdateHint',
    'download',
    'downloadStarting',
    'downloadStarted',
    'downloadFailed',
    'downloadChecksumMismatch',
    'downloadRecommended',
    'downloadAURHint',
    'changelog',
    'noChangelog',
    'later',
    'linuxUpdateHint',
    'saved',
    'selectSyncFolderTitle',
    'selectObsidianVaultTitle',
    'system',
    'light',
    'dark',
    'eink',
    'nord',
    'catppuccinMacchiato',
    'dracula',
    'sepia',
    'oled',
    'close',
] as const;

export type SettingsLabels = Record<(typeof SETTINGS_LABEL_KEYS)[number], string>;

// Maps a settings label key to its i18n key when it isn't simply
// `settings.<key>` — either because the string is shared with another part
// of the app (e.g. `back` -> `common.back`) or core spells it differently.
export const labelKeyOverrides: Partial<Record<keyof SettingsLabels, string>> = {
    cancel: 'common.cancel',
    sandboxWorkspace: 'sandbox.open',
    sandboxDescription: 'sandbox.description',
    sandboxSwitching: 'sandbox.switching',
    sandboxSwitchFailed: 'sandbox.switchFailed',
    sandboxConfirmTitle: 'sandbox.confirmTitle',
    sandboxConfirmDescription: 'sandbox.confirmDescription',
    sandboxEnter: 'sandbox.enter',
    back: 'common.back',
    // Sidebar-view checkboxes reuse the sidebar's own labels so every locale
    // is covered without new strings.
    navAgenda: 'nav.agenda',
    navSomeday: 'nav.someday',
    navWaiting: 'nav.waiting',
    navReference: 'nav.reference',
    navCalendar: 'nav.calendar',
    navReview: 'nav.review',
    navContexts: 'nav.contexts',
    navBoard: 'nav.board',
    navTimeline: 'nav.timeline',
    navHistory: 'nav.history',
    navTrash: 'nav.trash',
    tasks: 'calendar.tasks',
    projects: 'projects.title',
    settingsSaveFailed: 'settings.feedback.saveFailed',
    pomodoroAutoStartNotice: 'settings.gtdMobile.pomodoroWillNowAdvancePhasesAutomatically',
    // "Auto" is already translated for text direction; the feed color picker
    // means the same thing (follow the source), so no new locale key.
    calendarColorAuto: 'taskEdit.textDirection.auto',
    close: 'common.close',
    inboxModeGuided: 'process.modeGuided',
    inboxModeQuick: 'process.modeQuick',
    keybindings: 'keybindings.helpTitle',
    keybindingsDesc: 'settings.keybindingsDesc',
    keybindingStandard: 'keybindings.style.standard',
    keybindingVim: 'keybindings.style.vim',
    keybindingEmacs: 'keybindings.style.emacs',
    viewShortcuts: 'keybindings.openHelp',
    dateFormat: 'settings.dateFormat',
    dateFormatSystem: 'settings.dateFormatSystem',
    dateFormatDmy: 'settings.dateFormatDmy',
    dateFormatMdy: 'settings.dateFormatMdy',
    dateFormatYmd: 'settings.dateFormatYmd',
    calendarSystem: 'settings.calendarSystem',
    calendarSystemGregorian: 'settings.calendarSystemGregorian',
    calendarSystemJalali: 'settings.calendarSystemJalali',
    timeFormat: 'settings.timeFormat',
    timeFormatSystem: 'settings.timeFormatSystem',
    timeFormat12h: 'settings.timeFormat12h',
    timeFormat24h: 'settings.timeFormat24h',
    taskEditorLayoutReset: 'settings.resetToDefault',
    autoArchiveDayUnit: 'common.days',
    syncEncryptionCancel: 'common.cancel',
    taskEditorFieldStatus: 'taskEdit.statusLabel',
    taskEditorFieldProject: 'taskEdit.projectLabel',
    taskEditorFieldSection: 'taskEdit.sectionLabel',
    taskEditorFieldArea: 'taskEdit.areaLabel',
    taskEditorFieldPriority: 'taskEdit.priorityLabel',
    taskEditorFieldEnergyLevel: 'taskEdit.energyLevel',
    taskEditorFieldAssignedTo: 'taskEdit.assignedTo',
    taskEditorFieldContexts: 'taskEdit.contextsLabel',
    taskEditorFieldDescription: 'taskEdit.descriptionLabel',
    taskEditorFieldLocation: 'taskEdit.locationLabel',
    taskEditorFieldTags: 'taskEdit.tagsLabel',
    taskEditorFieldTimeEstimate: 'taskEdit.timeEstimateLabel',
    taskEditorFieldRecurrence: 'taskEdit.recurrenceLabel',
    taskEditorFieldStartTime: 'taskEdit.startDateLabel',
    taskEditorFieldDueDate: 'taskEdit.dueDateLabel',
    taskEditorFieldReviewAt: 'taskEdit.reviewDateLabel',
    taskEditorFieldAttachments: 'attachments.title',
    taskEditorFieldChecklist: 'taskEdit.checklist',
    taskEditorFieldTextDirection: 'taskEdit.textDirectionLabel',
    taskEditorSectionBasic: 'taskEdit.basic',
    taskEditorSectionScheduling: 'taskEdit.scheduling',
    taskEditorSectionOrganization: 'taskEdit.organization',
    taskEditorSectionDetails: 'taskEdit.details',
} as const;

// The `t` prop every settings page reads. One loop, so SettingsView and the
// English-only variant below cannot drift apart on either the key mapping or
// what happens when a locale is missing the key.
export function buildSettingsLabels(translate: TranslateFn): SettingsLabels {
    const result = {} as SettingsLabels;
    SETTINGS_LABEL_KEYS.forEach((key) => {
        // No explicit fallback: resolveI18nText already falls through to the
        // English copy and then to the key itself.
        result[key] = resolveI18nText(translate, labelKeyOverrides[key] ?? `settings.${key}`);
    });
    return result;
}

// English settings labels. Used by settings page tests that need a real (not
// mocked) SettingsLabels object; components should get `t` from SettingsView
// instead. `t` returns the key on a miss, so an identity translate misses
// every key and resolveI18nText falls through to the English copy.
export function getEnglishSettingsLabels(): SettingsLabels {
    return buildSettingsLabels((key) => key);
}

// The settings search index itself lives in core
// (packages/core/src/settings-search-keys.ts) and is consumed here through
// ./settings-search — this module only owns the `t` vocabulary the pages read.
